/**
 * Lazy WASM loader and typed async wrappers.
 *
 * The pkg directory is generated by running `bash scripts/build-wasm.sh` with
 * the output pointed at this directory:
 *
 *   wasm-pack build --release --target web \
 *     --out-dir apps/web/src/lib/wasm/pkg
 *
 * Until the pkg exists every function returns a descriptive error rather than
 * throwing, so the UI can show a graceful "WASM engine not loaded" message.
 */

import type {
  BacktestResult,
  BlackLittermanResult,
  BootstrapResult,
  FrontierResult,
  MonteCarloParams,
  MonteCarloResult,
  RiskMetrics,
  SolveFrontierParams,
  ViewInput,
  WalkforwardConfig,
  WalkforwardResult,
} from './types';

// ---------------------------------------------------------------------------
// Module-level singleton
// ---------------------------------------------------------------------------

type WasmModule = typeof import('./pkg/engine_wasm');

let _wasm: WasmModule | null = null;
let _initPromise: Promise<WasmModule | null> | null = null;

async function loadWasm(): Promise<WasmModule | null> {
  if (_wasm) return _wasm;
  if (_initPromise) return _initPromise;

  _initPromise = (async () => {
    try {
      const mod = await import('./pkg/engine_wasm');
      await mod.default(); // initialise the WASM binary
      _wasm = mod;
      return mod;
    } catch {
      // pkg not built yet or browser doesn't support WASM
      _initPromise = null;
      return null;
    }
  })();

  return _initPromise;
}

/** Returns true once the WASM module has been loaded successfully. */
export async function isEngineReady(): Promise<boolean> {
  const mod = await loadWasm();
  return mod !== null;
}

// ---------------------------------------------------------------------------
// JSON helpers
// ---------------------------------------------------------------------------

/** Parse a WASM JSON response, throwing if it contains an "error" field. */
function parseResult<T>(json: string): T {
  const parsed = JSON.parse(json) as T & { error?: string };
  if ('error' in parsed && parsed.error) {
    throw new Error(parsed.error as string);
  }
  return parsed;
}

/** Convert a JSON number-or-null to number | null. */
const num = (v: unknown): number | null =>
  v === null || v === undefined ? null : (v as number);

/** Convert a JSON array of numbers/nulls to Float64Array, replacing null → NaN. */
function toF64(arr: (number | null)[]): Float64Array {
  const out = new Float64Array(arr.length);
  for (let i = 0; i < arr.length; i++) {
    out[i] = arr[i] === null ? NaN : (arr[i] as number);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Guard: ensure WASM is loaded, throw a friendly error otherwise
// ---------------------------------------------------------------------------

const NOT_LOADED = 'WASM engine not loaded — run build-wasm.sh first';

async function wasm(): Promise<WasmModule> {
  const mod = await loadWasm();
  if (!mod) throw new Error(NOT_LOADED);
  return mod;
}

// ---------------------------------------------------------------------------
// Exported async wrappers
// ---------------------------------------------------------------------------

/**
 * Trace the efficient frontier and return the portfolios with statistics.
 * The returned weights are row-major (nPoints × nAssets).
 */
export async function solveFrontier(
  params: SolveFrontierParams,
): Promise<FrontierResult> {
  const m = await wasm();
  const json = m.solve_frontier(
    params.returns,
    params.nPeriods,
    params.nAssets,
    params.nPts,
    params.longOnly,
    params.lb,
    params.ub,
    params.rf,
    params.ppy,
  );
  const r = parseResult<{
    weights: (number | null)[];
    risks: (number | null)[];
    returns: (number | null)[];
    sharpes: (number | null)[];
    best_idx: number | null;
    n_portfolios: number;
    n_assets: number;
  }>(json);
  return {
    weights: toF64(r.weights),
    risks: toF64(r.risks),
    returns: toF64(r.returns),
    sharpes: toF64(r.sharpes),
    bestIdx: r.best_idx,
    nPoints: r.n_portfolios,
    nAssets: r.n_assets,
  };
}

/**
 * Compute HRP weights.
 * @param returns Row-major returns (nPeriods × nAssets).
 */
export async function solveHrp(
  returns: Float64Array,
  nPeriods: number,
  nAssets: number,
  tickers: string[],
): Promise<Float64Array> {
  const m = await wasm();
  const json = m.solve_hrp(
    returns,
    nPeriods,
    nAssets,
    JSON.stringify(tickers),
  );
  const r = parseResult<{ weights: (number | null)[] }>(json);
  return toF64(r.weights);
}

/**
 * Compute Equal Risk Contribution weights.
 * @param cov Row-major covariance matrix (nAssets × nAssets).
 */
export async function solveRiskParity(
  cov: Float64Array,
  nAssets: number,
  lb: number,
  ub: number,
): Promise<Float64Array> {
  const m = await wasm();
  const json = m.solve_risk_parity(cov, nAssets, lb, ub);
  const r = parseResult<{ weights: (number | null)[] }>(json);
  return toF64(r.weights);
}

/**
 * Minimise CVaR at confidence `alpha`.
 * @param returns Row-major returns (nPeriods × nAssets).
 */
export async function solveCvar(
  returns: Float64Array,
  nPeriods: number,
  nAssets: number,
  alpha: number,
  longOnly: boolean,
  lb: number,
  ub: number,
): Promise<Float64Array> {
  const m = await wasm();
  const json = m.solve_cvar(
    returns,
    nPeriods,
    nAssets,
    alpha,
    longOnly,
    lb,
    ub,
  );
  const r = parseResult<{ weights: (number | null)[] }>(json);
  return toF64(r.weights);
}

/**
 * Robust MVO via SOCP.
 * @param returns Row-major returns (nPeriods × nAssets).
 */
export async function solveRobust(
  returns: Float64Array,
  nPeriods: number,
  nAssets: number,
  gamma: number,
  longOnly: boolean,
  lb: number,
  ub: number,
  ppy: number = 252,
): Promise<Float64Array> {
  const m = await wasm();
  const json = m.solve_robust(
    returns,
    nPeriods,
    nAssets,
    gamma,
    longOnly,
    lb,
    ub,
    ppy,
  );
  const r = parseResult<{ weights: (number | null)[] }>(json);
  return toF64(r.weights);
}

/** Run a single-portfolio GBM Monte Carlo simulation. */
export async function runMonteCarlo(
  params: MonteCarloParams,
): Promise<MonteCarloResult> {
  const m = await wasm();
  const json = m.run_monte_carlo(JSON.stringify(params));
  const r = parseResult<Record<string, number | null>>(json);
  return {
    mean: num(r.mean),
    median: num(r.median),
    p5: num(r.p5),
    p25: num(r.p25),
    p75: num(r.p75),
    p95: num(r.p95),
    std: num(r.std),
    probLoss: num(r.prob_loss),
  };
}

/**
 * Run a static (buy-and-hold) backtest.
 * @param returns Row-major returns (nPeriods × nAssets).
 */
export async function runBacktestStatic(
  returns: Float64Array,
  nPeriods: number,
  nAssets: number,
  weights: Float64Array,
  includeEw: boolean = true,
): Promise<BacktestResult> {
  const m = await wasm();
  const json = m.run_backtest_static(
    returns,
    nPeriods,
    nAssets,
    weights,
    includeEw,
  );
  const r = parseResult<{
    portfolio_equity: (number | null)[];
    portfolio_returns: (number | null)[];
    portfolio_dd: (number | null)[];
    ew_equity: (number | null)[] | null;
    ew_dd: (number | null)[] | null;
  }>(json);
  return {
    portfolioEquity: toF64(r.portfolio_equity),
    portfolioReturns: toF64(r.portfolio_returns),
    portfolioDD: toF64(r.portfolio_dd),
    ewEquity: r.ew_equity ? toF64(r.ew_equity) : null,
    ewDD: r.ew_dd ? toF64(r.ew_dd) : null,
  };
}

/**
 * Run a walk-forward backtest with rolling-window re-optimisation.
 * @param returns Row-major returns (nPeriods × nAssets).
 */
export async function runBacktestWalkforward(
  returns: Float64Array,
  nPeriods: number,
  nAssets: number,
  config: WalkforwardConfig = {},
): Promise<WalkforwardResult> {
  const m = await wasm();
  const json = m.run_backtest_walkforward(
    returns,
    nPeriods,
    nAssets,
    JSON.stringify(config),
  );
  const r = parseResult<{
    portfolio_equity: (number | null)[];
    portfolio_returns: (number | null)[];
    portfolio_dd: (number | null)[];
    weights_history: (number | null)[];
    weights_shape: [number, number];
    rebalance_indices: number[];
    ew_equity: (number | null)[] | null;
  }>(json);
  return {
    portfolioEquity: toF64(r.portfolio_equity),
    portfolioReturns: toF64(r.portfolio_returns),
    portfolioDD: toF64(r.portfolio_dd),
    weightsHistory: toF64(r.weights_history),
    weightsShape: r.weights_shape,
    rebalanceIndices: r.rebalance_indices,
    ewEquity: r.ew_equity ? toF64(r.ew_equity) : null,
  };
}

/**
 * Compute annualised performance metrics from a returns series + weights.
 *
 * Computes portfolio equity from (returns × weights) internally before
 * passing to the WASM `compute_risk_metrics` function.
 *
 * @param returns Row-major returns (nPeriods × nAssets).
 */
export async function computeRiskMetrics(
  returns: Float64Array,
  nPeriods: number,
  nAssets: number,
  weights: Float64Array,
  _alpha: number = 0.95,   // reserved for future use
  rf: number = 0,
  ppy: number = 252,
): Promise<RiskMetrics> {
  const m = await wasm();

  // Build portfolio equity from returns × weights in TypeScript
  const equity = new Float64Array(nPeriods + 1);
  equity[0] = 1;
  for (let t = 0; t < nPeriods; t++) {
    let portRet = 0;
    for (let a = 0; a < nAssets; a++) {
      portRet += returns[t * nAssets + a] * weights[a];
    }
    equity[t + 1] = equity[t] * (1 + portRet);
  }

  const json = m.compute_risk_metrics(equity, rf, ppy);
  const r = parseResult<Record<string, number | null>>(json);
  return {
    cagr: num(r.cagr),
    annReturn: num(r.ann_return),
    annVol: num(r.ann_vol),
    maxDd: num(r.max_dd),
    var95: num(r.var_95),
    cvar95: num(r.cvar_95),
  };
}

/**
 * Compute the Pearson correlation matrix.
 * @param returns Row-major returns (nPeriods × nAssets).
 * @returns Flat row-major correlation matrix (nAssets × nAssets).
 */
export async function computeCorrelation(
  returns: Float64Array,
  nPeriods: number,
  nAssets: number,
): Promise<Float64Array> {
  const m = await wasm();
  const json = m.compute_correlation(returns, nPeriods, nAssets);
  const r = parseResult<{ corr: (number | null)[] }>(json);
  return toF64(r.corr);
}

/**
 * Black-Litterman model: blend market equilibrium returns with investor views.
 *
 * @param cov          Row-major annualised covariance (nAssets × nAssets).
 * @param nAssets      Number of assets.
 * @param marketWeights Market-cap or equal weights (length = nAssets).
 * @param rf           Risk-free rate.
 * @param marketReturn Expected market portfolio return.
 * @param views        Investor views (empty = pure equilibrium).
 * @param tau          Prior uncertainty scalar (typically 0.05).
 */
export async function solveBlackLitterman(
  cov: Float64Array,
  nAssets: number,
  marketWeights: Float64Array,
  rf: number,
  marketReturn: number,
  views: ViewInput[],
  tau: number,
  longOnly: boolean,
  lb: number,
  ub: number,
  nPts: number,
): Promise<BlackLittermanResult> {
  const m = await wasm();

  // Pack views into flat array: [n_views, per view: n_picks, idx0, w0, …, ret, conf]
  const packed = packViews(views);

  const json = m.solve_black_litterman(
    cov,
    nAssets,
    marketWeights,
    rf,
    marketReturn,
    packed,
    tau,
    longOnly,
    lb,
    ub,
    nPts,
  );
  const r = parseResult<{
    weights: (number | null)[];
    risks: (number | null)[];
    returns: (number | null)[];
    sharpes: (number | null)[];
    best_idx: number | null;
    n_portfolios: number;
    n_assets: number;
    implied_returns: (number | null)[];
    posterior_mu: (number | null)[];
  }>(json);

  return {
    weights: toF64(r.weights),
    risks: toF64(r.risks),
    returns: toF64(r.returns),
    sharpes: toF64(r.sharpes),
    bestIdx: r.best_idx,
    nPoints: r.n_portfolios,
    nAssets: r.n_assets,
    impliedReturns: toF64(r.implied_returns),
    posteriorMu: toF64(r.posterior_mu),
  };
}

/** Pack ViewInput[] into the flat format expected by the Rust WASM bridge. */
function packViews(views: ViewInput[]): Float64Array {
  if (views.length === 0) return new Float64Array(0);
  const parts: number[] = [views.length];
  for (const v of views) {
    parts.push(v.assetIndices.length);
    for (let i = 0; i < v.assetIndices.length; i++) {
      parts.push(v.assetIndices[i]);
      parts.push(v.weights[i] ?? 1);
    }
    parts.push(v.expectedReturn);
    parts.push(v.confidence);
  }
  return new Float64Array(parts);
}

/** Block-bootstrap Sharpe ratio confidence interval. */
export async function bootstrapSharpe(
  returns: Float64Array,
  rfPerPeriod: number,
  nBoot: number,
  blockSize: number,
  ci: number,
  seed: number,
): Promise<BootstrapResult> {
  const m = await wasm();
  const json = m.bootstrap_sharpe(
    returns,
    rfPerPeriod,
    nBoot,
    blockSize,
    ci,
    BigInt(seed),
  );
  const r = parseResult<Record<string, number | null>>(json);
  return {
    mean: num(r.mean),
    ciLower: num(r.ci_lower),
    ciUpper: num(r.ci_upper),
    nSamples: (r.n_samples ?? 0) as number,
  };
}
